<?php
/**
 * IeYandexMarketExportService Russian Lexicon Entries for ieYandexMarket
 *
 * @package ieyandexmarket
 * @subpackage lexicon
 */

$_lang['ieyandexmarket_ieyandexmarketexportservice_name'] = 'Экспорт YandexMarket';
$_lang['ieyandexmarket_ieyandexmarketexportservice_description'] = '';
$_lang['ieyandexmarket_ieyandexmarketexportservice_setting_tab'] = 'Яндекс.Маркет';
$_lang['ieyandexmarket_ieyandexmarketexportservice_setting_store_name'] = 'Короткое название магазина';
$_lang['ieyandexmarket_ieyandexmarketexportservice_setting_store_name_help'] = '';
$_lang['ieyandexmarket_ieyandexmarketexportservice_setting_store_company'] = 'Полное наименование компании, владеющей магазином';
$_lang['ieyandexmarket_ieyandexmarketexportservice_setting_store_company_help'] = '';
$_lang['ieyandexmarket_ieyandexmarketexportservice_setting_store_email'] = 'E-mail';
$_lang['ieyandexmarket_ieyandexmarketexportservice_setting_store_email_help'] = '';
$_lang['ieyandexmarket_ieyandexmarketexportservice_setting_store_default_currency'] = 'Основная валюта';
$_lang['ieyandexmarket_ieyandexmarketexportservice_setting_store_default_currency_help'] = '';
$_lang['ieyandexmarket_ieyandexmarketexportservice_setting_store_rate_currency'] = 'Множитель курса валюты';
$_lang['ieyandexmarket_ieyandexmarketexportservice_setting_store_rate_currency_help'] = 'Указывает курс валюты к курсу основной валюты, взятой за единицу. СВ — курс по банку той страны, к которой относится магазин по Своему региону, указанному в Партнерском интерфейсе Яндекс.Маркета.';
$_lang['ieyandexmarket_ieyandexmarketexportservice_setting_store_currencies'] = 'Валюты магазина';
$_lang['ieyandexmarket_ieyandexmarketexportservice_setting_store_currencies_help'] = 'По умолчанию - весь список валют для Яндекс.Маркета: RUB,EUR,USD,UAH,BYR,KZT';
$_lang['ieyandexmarket_ieyandexmarketexportservice_setting_delivery_options_help'] = 'Общие условия доставки для всех товаров. Тэг <a href="https://yandex.ru/support/partnermarket/elements/delivery-options.html" target="_blank">delivery-options</a> может содержать до пяти элементов option для указания разных видов и условий доставки (например, обычная, экспресс и др.).';
$_lang['ieyandexmarket_ieyandexmarketexportservice_setting_delivery_default'] = 'Значение по умолчанию';
$_lang['ieyandexmarket_ieyandexmarketexportservice_setting_delivery_default_help'] = 'Возможность курьерской доставки (по всем регионам, в которые доставляет магазин). Тэг <a href="https://yandex.ru/support/partnermarket/elements/delivery.html" target="_blank">delivery</a>.';
$_lang['ieyandexmarket_ieyandexmarketexportservice_setting_delivery_field'] = 'Название поля с значением';
$_lang['ieyandexmarket_ieyandexmarketexportservice_setting_delivery_field_help'] = 'Укажите название поля, значение из которое будет использовано для тэга <a href="https://yandex.ru/support/partnermarket/elements/delivery.html" target="_blank">delivery</a>. Если настройка не задана, для всех товаров значение тэга будет установлено на основании опции "Значение по умолчанию".';
$_lang['ieyandexmarket_ieyandexmarketexportservice_setting_delivery_field_options'] = 'Название поля товара с данными для delivery-options';
$_lang['ieyandexmarket_ieyandexmarketexportservice_setting_delivery_field_options_help'] = 'Укажите название поля, которое будет содержать данные для тэга delivery-options входящего в тэг <a href="https://yandex.ru/support/partnermarket/offers.html" target="_blank">offer</a>. Данные должны быть в JSON формате. <strong>Пример</strong>: [{"cost":200,"days":"2-3","order_before":"18:00"},{"cost":300,"days":"1-2","order_before":"18:00"}]';
$_lang['ieyandexmarket_ieyandexmarketexportservice_setting_available_default'] = 'Значение по умолчанию';
$_lang['ieyandexmarket_ieyandexmarketexportservice_setting_available_default_help'] = 'Тэг <a href="https://market.yandex.ru/partners/news/element-available" target="_blank">available</a>';
$_lang['ieyandexmarket_ieyandexmarketexportservice_setting_available_field'] = 'Название поля с значением';
$_lang['ieyandexmarket_ieyandexmarketexportservice_setting_available_field_help'] = 'Укажите название поля, значение из которое будет использовано для тэга <a href="https://market.yandex.ru/partners/news/element-available" target="_blank">available</a>. Если настройка не задана, для всех товаров значение тэга будет установлено на основании опции "Значение по умолчанию".';
$_lang['ieyandexmarket_ieyandexmarketexportservice_setting_pickup_options'] = '';
$_lang['ieyandexmarket_ieyandexmarketexportservice_setting_pickup_options_help'] = 'Общие условия самовывоза по региону магазина (сроки, стоимость). Тэг <a href="https://yandex.ru/support/partnermarket/elements/pickup-options.html" target="_blank">pickup-options</a>.';
$_lang['ieyandexmarket_ieyandexmarketexportservice_setting_pickup_default'] = 'Значение по умолчанию';
$_lang['ieyandexmarket_ieyandexmarketexportservice_setting_pickup_default_help'] = 'Возможность самовывоза из пунктов выдачи (во всех регионах, в которые доставляет магазин). Тэг <a href="https://yandex.ru/support/partnermarket/elements/delivery.html#pickup" target="_blank">pickup</a>.';
$_lang['ieyandexmarket_ieyandexmarketexportservice_setting_pickup_field'] = 'Название поля с значением';
$_lang['ieyandexmarket_ieyandexmarketexportservice_setting_pickup_field_help'] = 'Укажите название поля, значение из которое будет использовано для тэга <a href="https://yandex.ru/support/partnermarket/elements/delivery.html#pickup" target="_blank">pickup</a>. Если настройка не задана, для всех товаров значение тэга будет установлено на основании опции "Значение по умолчанию".';
$_lang['ieyandexmarket_ieyandexmarketexportservice_setting_pickup_field_options'] = 'Название поля с данными для pickup-options';
$_lang['ieyandexmarket_ieyandexmarketexportservice_setting_pickup_field_options_help'] = 'Укажите название поля, которое будет содержать данные для тэга <a href="https://yandex.ru/support/partnermarket/elements/pickup-options.html" target="_blank">pickup-options</a> входящего в тэг <a href="https://yandex.ru/support/partnermarket/offers.html" target="_blank">offer</a>. Данные должны быть в JSON формате. <strong>Пример</strong>: [{"cost":200,"days":"2-3","order_before":"18:00"},{"cost":300,"days":"1-2","order_before":"18:00"}]';
$_lang['ieyandexmarket_ieyandexmarketexportservice_setting_sales_notes_default'] = 'Значение по умолчанию';
$_lang['ieyandexmarket_ieyandexmarketexportservice_setting_sales_notes_default_help'] = '';
$_lang['ieyandexmarket_ieyandexmarketexportservice_setting_sales_notes_field'] = 'Название поля с значением';
$_lang['ieyandexmarket_ieyandexmarketexportservice_setting_sales_notes_field_help'] = 'Укажите название поля, значение из которое будет использовано для тэга <a href="https://yandex.ru/support/partnermarket/elements/sales_notes.html" target="_blank">sales_notes</a>.';
$_lang['ieyandexmarket_ieyandexmarketexportservice_setting_group_id_field'] = 'Название поля c значением для group_id';
$_lang['ieyandexmarket_ieyandexmarketexportservice_setting_group_id_field_help'] = 'Укажите название поля, значение из которое будет использовано для тэга <a href="https://yandex.ru/support/partnermarket/elements/sales_notes.html" target="_blank">group_id</a>';
$_lang['ieyandexmarket_ieyandexmarketexportservice_setting_country_of_origin_field'] = 'Название поля c значением для country_of_origin';
$_lang['ieyandexmarket_ieyandexmarketexportservice_setting_country_of_origin_field_help'] = 'Укажите название поля, значение из которое будет использовано для тэга <a href="https://yandex.ru/support/partnermarket/elements/sales_notes.html" target="_blank">country_of_origin</a>';
$_lang['ieyandexmarket_ieyandexmarketexportservice_setting_vendor_code_field'] = 'Название поля для vendorCode';
$_lang['ieyandexmarket_ieyandexmarketexportservice_setting_vendor_code_field_help'] = 'Укажите название поля, значение из которое будет использовано для тэга <a href="https://yandex.ru/support/partnermarket/offers.html" target="_blank">vendorCode</a>.';
$_lang['ieyandexmarket_ieyandexmarketexportservice_setting_model_field'] = 'Название поля для model';
$_lang['ieyandexmarket_ieyandexmarketexportservice_setting_model_field_help'] = 'Укажите название поля, значение из которое будет использовано для тэга <a href="https://yandex.ru/support/partnermarket/elements/vendor-name-model.html" target="_blank">model</a>.';
$_lang['ieyandexmarket_ieyandexmarketexportservice_setting_type_prefix_field'] = 'Название поля для typePrefix';
$_lang['ieyandexmarket_ieyandexmarketexportservice_setting_type_prefix_field_help'] = 'Укажите название поля, значение из которое будет использовано для тэга <a href="https://yandex.ru/support/partnermarket/elements/vendor-name-model.html" target="_blank">typePrefix</a>.';
$_lang['ieyandexmarket_ieyandexmarketexportservice_setting_expiry_field'] = 'Название поля для expiry';
$_lang['ieyandexmarket_ieyandexmarketexportservice_setting_expiry_field_help'] = 'Укажите название поля, значение из которое будет использовано для тэга <a href="https://yandex.ru/support/partnermarket/elements/vendor-name-model.html" target="_blank">expiry</a>.';
$_lang['ieyandexmarket_ieyandexmarketexportservice_setting_store_default'] = 'Значение по умолчанию';
$_lang['ieyandexmarket_ieyandexmarketexportservice_setting_store_default_help'] = '';
$_lang['ieyandexmarket_ieyandexmarketexportservice_setting_store_field'] = 'Название поля для store';
$_lang['ieyandexmarket_ieyandexmarketexportservice_setting_store_field_help'] = 'Укажите название поля, значение из которое будет использовано для тэга <a href="https://yandex.ru/support/partnermarket/elements/delivery.html#store" target="_blank">store</a>';
$_lang['ieyandexmarket_ieyandexmarketexportservice_setting_param_help'] = 'Укажите поля, по которым будут проставляться характеристики товара. Тег <a href="https://yandex.ru/support/partnermarket/elements/param.html" target="_blank">param</a>';
$_lang['ieyandexmarket_ieyandexmarketexportservice_setting_include_optionsprice2'] = 'Экспортировать модификации msOptionsPrice2';
$_lang['ieyandexmarket_ieyandexmarketexportservice_setting_include_optionsprice2_help'] = '';
$_lang['ieyandexmarket_ieyandexmarketexportservice_setting_include_saleprice'] = 'Экспортировать цены msSalePrice';
$_lang['ieyandexmarket_ieyandexmarketexportservice_setting_include_saleprice_help'] = '';
$_lang['ieyandexmarket_ieyandexmarketexportservice_setting_only_saleprice_price'] = 'Экспортировать только цены msSalePrice';
$_lang['ieyandexmarket_ieyandexmarketexportservice_setting_only_saleprice_price_help'] = 'Если выбрано "Да" то обычная цена товар не будет экспортироваться.';
$_lang['ieyandexmarket_ieyandexmarketexportservice_setting_exclude_saleprice_price'] = 'Исключить цены';
$_lang['ieyandexmarket_ieyandexmarketexportservice_setting_exclude_saleprice_price_help'] = 'Укажите название тегов цен msSalePrice которые следует исключить из экспорта.';
$_lang['ieyandexmarket_ieyandexmarketexportservice_setting_description_fields'] = 'Список названий полей';
$_lang['ieyandexmarket_ieyandexmarketexportservice_setting_description_fields_help'] = 'Выберите поля, из которых следует брать описание товара. Описание будет взято из первого найденного поля с текстом.';
$_lang['ieyandexmarket_ieyandexmarketexportservice_setting_description_allowed_tags'] = 'Допустимые теги в описании товара';
$_lang['ieyandexmarket_ieyandexmarketexportservice_setting_description_allowed_tags_help'] = 'Все теги которые не попали в список будут удалены.';
$_lang['ieyandexmarket_ieyandexmarketexportservice_setting_multicategories'] = 'Несколько категорий для товара';
$_lang['ieyandexmarket_ieyandexmarketexportservice_setting_multicategories_help'] = 'В оффер через, тег categoryId, будут добавлены все категории к которым относится товар. Данный формат поддерживаться сервисом <a href="https://soc-commerce.com/" target="_blank">soc-commerce.com</a>';
$_lang['ieyandexmarket_ieyandexmarketexportservice_setting_offer_type'] = 'Тип описания предложения';
$_lang['ieyandexmarket_ieyandexmarketexportservice_setting_offer_type_help'] = '';
$_lang['ieyandexmarket_ieyandexmarketexportservice_setting_fieldset_shop'] = 'Магазин';
$_lang['ieyandexmarket_ieyandexmarketexportservice_setting_fieldset_store'] = 'Покупка без предварительного заказа';
$_lang['ieyandexmarket_ieyandexmarketexportservice_setting_fieldset_currency'] = 'Валюта';
$_lang['ieyandexmarket_ieyandexmarketexportservice_setting_fieldset_delivery'] = 'Доставка';
$_lang['ieyandexmarket_ieyandexmarketexportservice_setting_fieldset_available'] = 'Наличие';
$_lang['ieyandexmarket_ieyandexmarketexportservice_setting_fieldset_pickup'] = 'Самовывоз';
$_lang['ieyandexmarket_ieyandexmarketexportservice_setting_fieldset_sales_notes'] = 'Самовывоз';
$_lang['ieyandexmarket_ieyandexmarketexportservice_setting_fieldset_vendor'] = 'Производитель';
$_lang['ieyandexmarket_ieyandexmarketexportservice_setting_fieldset_param'] = 'Характеристики товара';
$_lang['ieyandexmarket_ieyandexmarketexportservice_setting_fieldset_sales_notes'] = 'Условие продажи';
$_lang['ieyandexmarket_ieyandexmarketexportservice_setting_fieldset_description'] = 'Описание';
$_lang['ieyandexmarket_ieyandexmarketexportservice_setting_fieldset_saleprice'] = 'msSalePrice';
$_lang['ieyandexmarket_ieyandexmarketexportservice_setting_fieldset_other'] = 'Прочее';
$_lang['ieyandexmarket_param_btn_add'] = 'Добавить';
$_lang['ieyandexmarket_param_header_field'] = 'Поле';
$_lang['ieyandexmarket_param_header_name'] = 'Название';
$_lang['ieyandexmarket_param_header_unit'] = 'Единица измерения';
$_lang['ieyandexmarket_options_btn_add_option'] = 'Добавить опцию';
$_lang['ieyandexmarket_delivery_options_header_cost'] = 'Стоимость доставки';
$_lang['ieyandexmarket_delivery_options_header_days'] = 'Срок доставки';
$_lang['ieyandexmarket_delivery_options_header_order_before'] = 'Время, до которого нужно сделать заказ';
$_lang['ieyandexmarket_pickup_options_header_cost'] = 'Стоимость самовывоза';
$_lang['ieyandexmarket_pickup_options_header_days'] = 'Cрок поставки товара в пункт выдачи';
$_lang['ieyandexmarket_pickup_options_header_order_before'] = 'Время, до которого нужно сделать заказ';
$_lang['ieyandexmarket_offer_type_simple'] = 'Простой';
$_lang['ieyandexmarket_offer_type_custom'] = 'Произвольный';
$_lang['ieyandexmarket_offer_type_artist_title'] = 'Музыкальная и видео продукция';
$_lang['ieyandexmarket_offer_type_book'] = 'Книга';
$_lang['ieyandexmarket_offer_type_audiobook'] = 'Аудиокнига';
$_lang['ieyandexmarket_offer_type_event_ticket'] = 'Билеты на мероприятия';
$_lang['ieyandexmarket_offer_type_tour'] = 'Тур';
$_lang['ieyandexmarket_offer_type_сondition'] = '';
$_lang['ieyandexmarket_err_get_service_iegallery'] = 'Ошибка загрузки IeGallery';

