Msie.service.ieGalleryExportService = {
    getTabSettings: function (config) {
        return {
            title: _('iegallery_iegalleryexportservice_setting_tab'),
            id: 'iegallery-setting-tab-iegalleryexportservice',
            layout: 'form',
            items: [{
                xtype: 'iegallery-combo-gallery',
                fieldLabel: _('iegallery_iegalleryexportservice_setting_gallery_type'),
                description: '<b>gallery_type</b>',
                name: 'gallery_type',
                anchor: '100%'
            }, {
                xtype: 'label',
                html: _('iegallery_iegalleryexportservice_setting_gallery_type_help'),
                cls: 'desc-under'
            }, {
                xtype: 'msie-combo-boolean',
                fieldLabel: _('iegallery_iegalleryexportservice_setting_absolute_url'),
                description: '<b>gallery_absolute_url</b>',
                name: 'gallery_absolute_url',
                anchor: '100%'
            }, {
                xtype: 'label',
                html: _('iegallery_iegalleryexportservice_setting_absolute_url_help'),
                cls: 'desc-under'
            }, {
                xtype: 'msie-combo-boolean',
                fieldLabel: _('iegallery_iegalleryexportservice_setting_concatenate_images'),
                description: '<b>gallery_concatenate_images</b>',
                name: 'gallery_concatenate_images',
                anchor: '100%'
            }, {
                xtype: 'label',
                html: _('iegallery_iegalleryexportservice_setting_concatenate_images_help'),
                cls: 'desc-under'
            }, {
                xtype: 'msie-field',
                fieldLabel: _('iegallery_iegalleryexportservice_setting_image_delimiter'),
                description: '<b>gallery_image_delimiter</b>',
                name: 'gallery_image_delimiter',
                anchor: '100%'
            }, {
                xtype: 'label',
                html: _('iegallery_iegalleryexportservice_setting_image_delimiter_help'),
                cls: 'desc-under'
            }, {
                xtype: 'msie-combo-boolean',
                fieldLabel: _('iegallery_iegalleryexportservice_setting_add_images_to_archive'),
                description: '<b>gallery_add_images_to_archive</b>',
                name: 'gallery_add_images_to_archive',
                anchor: '100%'
            }, {
                xtype: 'label',
                html: _('iegallery_iegalleryexportservice_setting_add_images_to_archive_help'),
                cls: 'desc-under'
            }, {
                xtype: 'msie-combo-boolean',
                fieldLabel: _('iegallery_iegalleryexportservice_setting_copy_image'),
                description: '<b>gallery_copy_image</b>',
                name: 'gallery_copy_image',
                anchor: '100%'
            }, {
                xtype: 'label',
                html: _('iegallery_iegalleryexportservice_setting_copy_image_help'),
                cls: 'desc-under'
            }, {
                xtype: 'msie-field',
                fieldLabel: _('iegallery_iegalleryexportservice_setting_copy_image_path'),
                description: '<b>gallery_copy_image_path</b>',
                name: 'gallery_copy_image_path',
                anchor: '100%'
            }, {
                xtype: 'label',
                html: _('iegallery_iegalleryexportservice_setting_copy_image_path_help'),
                cls: 'desc-under'
            }, {
                xtype: 'numberfield',
                fieldLabel: _('iegallery_iegalleryimportservice_setting_limit'),
                description: '<b>gallery_limit</b>',
                name: 'gallery_limit',
                anchor: '100%'
            }, {
                xtype: 'label',
                html: _('iegallery_iegalleryimportservice_setting_limit_help'),
                cls: 'desc-under'
            }, {
                xtype: 'iegallery-combo-sortdir',
                fieldLabel: _('iegallery_iegalleryimportservice_setting_sortdir'),
                description: '<b>gallery_sortdir</b>',
                name: 'gallery_sortdir',
                anchor: '100%'
            }, {
                xtype: 'label',
                html: _('iegallery_iegalleryimportservice_setting_sortdir_help'),
                cls: 'desc-under'
            }, {
                xtype: Ext.ComponentMgr.types['modx-texteditor'] ? 'modx-texteditor' : 'textarea',
                mimeType: 'application/json',
                fieldLabel: _('iegallery_iegalleryexportservice_setting_attach_settings'),
                description: '<b>gallery_attach_settings</b>',
                name: 'gallery_attach_settings',
                height: 80,
                allowBlank: true,
                anchor: '100%'
            }, {
                xtype: 'label',
                html: _('iegallery_iegalleryexportservice_setting_attach_settings_help'),
                cls: 'desc-under'
            }

            ]
        };
    }
};